"""add hsn code to products

Revision ID: 7159455cb365
Revises: 017d166ac878
Create Date: 2026-09-15 21:41:09.739570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7159455cb365'
down_revision: Union[str, Sequence[str], None] = '017d166ac878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('hsn_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'hsn_code')
    # ### end Alembic commands ###
