"""add customer to bills

Revision ID: 9ef50d32cd7a
Revises: 8abff40d8acf
Create Date: 2026-09-13 18:50:01.412779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef50d32cd7a'
down_revision: Union[str, Sequence[str], None] = '8abff40d8acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
    'fk_bills_customer_id',
    'bills',
    'customers',
    ['customer_id'],
    ['id']
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
    'fk_bills_customer_id',
    'bills',
    type_='foreignkey'
)
    op.drop_column('bills', 'customer_id')
    # ### end Alembic commands ###
