"""create active bill sessions

Revision ID: ce6706dd71d3
Revises: 05bbb04980b0
Create Date: 2026-09-15 22:41:14.731664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6706dd71d3'
down_revision: Union[str, Sequence[str], None] = '05bbb04980b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_bill_sessions',
    sa.Column('session_key', sa.String(length=100), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_key'),
    sa.UniqueConstraint('bill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_bill_sessions')
    # ### end Alembic commands ###
