"""add hsn code to bill items

Revision ID: d6845f9154dd
Revises: 7159455cb365
Create Date: 2026-09-15 21:51:28.877525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6845f9154dd'
down_revision: Union[str, Sequence[str], None] = '7159455cb365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_items', sa.Column('hsn_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill_items', 'hsn_code')
    # ### end Alembic commands ###
